# Generated by Django 2.2.2 on 2019-09-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField()),
                ('tipo_dispesa', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=300)),
                ('forma_de_pagamento', models.CharField(max_length=10)),
                ('vencimento', models.DateField()),
                ('quitado', models.BooleanField()),
            ],
        ),
    ]
