# Generated by Django 2.2.2 on 2019-09-10 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartemento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(max_length=4)),
                ('qtdQuartos', models.IntegerField(max_length=4)),
                ('proprietario', models.CharField(max_length=50)),
                ('valorCondominio', models.IntegerField(max_length=10)),
            ],
        ),
    ]
