# Generated by Django 2.2.2 on 2019-09-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apartamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartemento',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='apartemento',
            name='qtdQuartos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='apartemento',
            name='valorCondominio',
            field=models.IntegerField(),
        ),
    ]
