# Generated by Django 2.2.2 on 2019-09-10 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apartamento', '0002_auto_20190909_2332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apartemento',
            new_name='Apartamento',
        ),
    ]
