# Generated by Django 2.2.2 on 2019-09-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apartamento', '0003_auto_20190909_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamento',
            name='valorCondominio',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
